version: '3.8'

services:
  server:
    container_name: server
    build:
      context: ./server
    environment:
      - NODE_ENV=production
    ports:
      - 3001:3001

  client:
    container_name: client
    build:
      context: ./client
    ports:
      - 3002:3002
